{
 "title": "API Log Analysis Dashboard",
 "time": { "from": "2025-06-17T19:41:57.564Z", "to": "2025-06-17T19:45:29.135Z" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "Accode", "label": "Accode" },
   { "name": "aggre_window", "label": "aggre_window(seconds)", "query": "10" },
   { "name": "ge", "label": "Greater than or equal to" },
   {
    "name": "action",
    "label": "Action(RegEx without special chars)"
   },
   { "name": "status_code", "label": "status_code(Number only)" },
   { "name": "DistinctFieldNameAnchor", "label": "field name anchor", "query": "parameters" },
   {
    "name": "measurement",
    "label": "Choose measurement",
    "query": "P3_SMS_API_application_logs_test,P3_API_application_logs_test,SG_NGINX_logs_test"
   },
   {
    "name": "bucket",
    "label": "Choose bucket",
    "query": "API-Log-Analysis-Parser-test,API-Log-Analysis-Parser-test2,API-Log-Analysis-Parser-test3,API-Log-Analysis-Parser-test4,API-Log-Analysis-SMSAPI,SG-NGINX-Log-Analysis"
   }
  ]
 },
 "panels": [
  {
   "title": "API requests count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total request count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> count()"
      }
     ]
    },
    {
     "title": "Message Level: INF - Count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"INF\" or r[\"level\"] == \"INFO\")\r\n  |> group(columns: [\"_measurement\", \"level\"])\r\n  |> count()"
      }
     ]
    },
    {
     "title": "Message Level: WRN - Count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"WRN\" or r[\"level\"] == \"WARN\")\r\n  |> group(columns: [\"_measurement\", \"level\"])\r\n  |> count()"
      }
     ]
    },
    {
     "title": "Message Level: ERR - Count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"ERROR\" or r[\"level\"] == \"ERR\")\r\n  |> group(columns: [\"_measurement\", \"level\"])\r\n  |> count()"
      }
     ]
    },
    {
     "title": "P3 SMS API request count (By Action)",
     "type": "barchart",
     "gridPos": { "h": 34, "w": 23, "x": 0, "y": 60 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> group(columns: [\"_measurement\", \"action\", \"_field\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    },
    {
     "title": "Action Requests Count, aggregation window: ${aggre_window}s",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 94 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: count, createEmpty: true)"
      }
     ]
    },
    {
     "title": "Counter requests (by Accode), Accept value: `Greater than or equal to` ",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 108 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] != \"\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    }
   ]
  },
  { "title": "Status code statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total request count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Status code: 200 - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"status_code\"] == \"200\")\r\n  |> group(columns: [\"_measurement\", \"status_code\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Status code: 404 - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"status_code\"] == \"404\")\r\n  |> group(columns: [\"_measurement\", \"status_code\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Status code: 503 - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"status_code\"] == \"503\")\r\n  |> group(columns: [\"_measurement\", \"status_code\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "P3 SMS API request count (By status code & action)",
   "type": "bargauge",
   "gridPos": { "h": 27, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"status_code\"] =~ /.*${status_code}/)\r\n  |> group(columns: [\"_measurement\", \"_field\", \"status_code\", \"action\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
    }
   ]
  },
  {
   "title": "Action Requests Count by `status_code`, aggregation window: ${aggre_window}s",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"status_code\"] =~ /.*${status_code}/)\r\n  |> group(columns: [\"_measurement\", \"action\", \"status_code\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Query for accode: ${Accode}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total request count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 606 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
      }
     ]
    },
    {
     "title": "Message Level: INF - Count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 606 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"INF\" or r[\"level\"] == \"INFO\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
      }
     ]
    },
    {
     "title": "Message Level: WRN - Count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 606 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"WARN\" or r[\"level\"] == \"WRN\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
      }
     ]
    },
    {
     "title": "Message Level: ERR - Count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 606 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"ERROR\" or r[\"level\"] == \"ERR\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
      }
     ]
    },
    {
     "title": "API request count group by action, Accode: ${Accode}",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 687 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> group(columns: [\"_measurement\", \"accode\", \"action\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    },
    {
     "title": "API request count group by action, Accode: ${Accode}, aggregation window: ${aggre_window}s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 695 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> aggregateWindow(\r\n    every: ${aggre_window}s,\r\n    fn: (column, tables=<-) => tables |> count(),\r\n    createEmpty: true\r\n  )"
      }
     ]
    },
    {
     "title": "Avg. response time, Accode: ${Accode}, aggregation window: ${aggre_window}s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 703 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"_field\", \"accode\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Min. response time, Accode: ${Accode}, aggregation window: ${aggre_window}s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 711 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"_field\", \"accode\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: min, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Max. response time, Accode: ${Accode}, aggregation window: ${aggre_window}s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 711 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"_field\", \"accode\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: max, createEmpty: false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Average response time statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average of response time by Action (ms)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 431 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Average of response time by Action (ms)",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 443 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> mean()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    },
    {
     "title": "Min of response time by Action (ms)",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 455 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> min()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    },
    {
     "title": "Max of response time by Action (ms)",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 455 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> max()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    }
   ]
  }
 ]
}