{
 "title": "API Log Analysis Dashboard Template",
 "time": { "from": "2025-05-19T02:25:22.705Z", "to": "2025-05-19T05:07:15.142Z" },
 "templating": {
  "list": [
   { "name": "Accode", "label": "Accode", "query": "P586293" },
   { "name": "aggre_window", "label": "aggre_window(seconds)", "query": "60" },
   { "name": "ge", "label": "Greater than or equal to", "query": "110" },
   {
    "name": "action",
    "label": "Action(RegEx without special chars)"
   },
   { "name": "DistinctFieldNameAnchor", "label": "field name anchor", "query": "parameters" },
   {
    "name": "measurement",
    "label": "Choose measurement",
    "query": "P3_SMS_API_application_logs_test,P3_API_application_logs_test"
   },
   {
    "name": "bucket",
    "label": "Choose bucket",
    "query": "API-Log-Analysis-Parser-test,API-Log-Analysis-Parser-test2,API-Log-Analysis-Parser-test4"
   }
  ]
 },
 "panels": [
  { "title": "API requests count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total request count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Message Level: INF - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"INF\" or r[\"level\"] == \"INFO\")\r\n  |> group(columns: [\"_measurement\", \"level\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Message Level: WRN - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"WRN\" or r[\"level\"] == \"WARN\")\r\n  |> group(columns: [\"_measurement\", \"level\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Message Level: ERR - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"ERROR\" or r[\"level\"] == \"ERR\")\r\n  |> group(columns: [\"_measurement\", \"level\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "P3 SMS API request count (By Action)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> group(columns: [\"_measurement\", \"action\", \"_field\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
    }
   ]
  },
  {
   "title": "Action Requests Count, aggregation window: ${aggre_window}s",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Counter requests (by Accode), Accept value: `Greater than or equal to` ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] != \"\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
    }
   ]
  },
  { "title": "Query for accode: ${Accode}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Total request count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Message Level: INF - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"INF\" or r[\"level\"] == \"INFO\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Message Level: WRN - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"WARN\" or r[\"level\"] == \"WRN\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Message Level: ERR - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"ERROR\" or r[\"level\"] == \"ERR\")\r\n  |> group(columns: [\"_measurement\", \"accode\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "API request count group by action, Accode: ${Accode}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${DistinctFieldNameAnchor}\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> group(columns: [\"_measurement\", \"accode\", \"action\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
    }
   ]
  },
  {
   "title": "API request count group by action, Accode: ${Accode}, aggregation window: ${aggre_window}s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> aggregateWindow(\r\n    every: ${aggre_window}s,\r\n    fn: (column, tables=<-) => tables |> count(),\r\n    createEmpty: true\r\n  )"
    }
   ]
  },
  {
   "title": "Avg. response time, Accode: ${Accode}, aggregation window: ${aggre_window}s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 71 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"_field\", \"accode\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Min. response time, Accode: ${Accode}, aggregation window: ${aggre_window}s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"_field\", \"accode\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: min, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Max. response time, Accode: ${Accode}, aggregation window: ${aggre_window}s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"accode\"] == \"${Accode}\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"_field\", \"accode\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Average response time statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average of response time by Action (ms)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 88 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> filter(fn: (r) => r[\"action\"] =~ /.*${action}/)\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> aggregateWindow(every: ${aggre_window}s, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Average of response time by Action (ms)",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 100 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> mean()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    },
    {
     "title": "Min of response time by Action (ms)",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 112 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> min()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    },
    {
     "title": "Max of response time by Action (ms)",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 112 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"duration_ms\")\r\n  |> group(columns: [\"_measurement\", \"action\"])\r\n  |> max()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    }
   ]
  }
 ]
}